### ISSUE TITLE
关于覆盖率不准的问题

### ISSUE THREAD

**Issue by jmx164491960** [CodeLittlePrince/vue-construct#1]
你好，我也是遇到karma覆盖率0的问题，然后看到你的文章把按你的配置改了一下preprocessors，覆盖率确实出来了，但是有两个问题，我跑了一下你的vue-construct发现存在这样的问题：
1.覆盖率不准确，里面还额外包含了很多webpack打包的代码
2.打开coverage/index.html，所有.vue，.js的代码都堆积在index.js了，当项目大了的时候这个index.html打开代码太多，根本看不到某一个模块的测试覆盖率详细情况。

想请教一下有没有什么解决办法？

**Comment by CodeLittlePrince** [comment]
第一个问题，覆盖率包含webpack打包的代码这个问题，因为很多高级语法并不是每个游览器都支持。所以运行用例之前都是经过编译的。因此覆盖率就得以编译之后为准，但从百分比来说，应该差不了多少。我暂时也不知道是不是又更好的方法。不知道你有没有线索，希望知道了可以告诉我下。
第二个问题，之前倒是没有考虑过，因为其实我只会测试common/js中的代码，所以不会太多，最近很忙，以后可以研究研究。

**Comment by CodeLittlePrince** [comment]
@jmx164491960 第一个问题，覆盖率包含webpack打包的代码这个问题，因为很多高级语法并不是每个游览器都支持。所以运行用例之前都是经过编译的。因此覆盖率就得以编译之后为准，但从百分比来说，应该差不了多少。我暂时也不知道是不是又更好的方法。不知道你有没有线索，希望知道了可以告诉我下。
第二个问题，之前倒是没有考虑过，因为其实我只会测试common/js中的代码，所以不会太多，最近很忙，以后可以研究研究。

**Comment by CodeLittlePrince** [comment]
@jmx164491960 赞！我晚上也试试，同学你最近在搞前端工程这方面吗？能加个Q多交流交流不，我Q：1006312908

**Comment by jmx164491960** [comment]
可以啊，最近手上工作不多，比较闲，所以研究起来单元测试了。

**Comment by CodeLittlePrince** [comment]
沉迷业务醉生梦死，，，终于有时间搞业余了，啊哈哈，已解决

**Comment by yhlben** [comment]
> 沉迷业务醉生梦死，，，终于有时间搞业余了，啊哈哈，已解决

@CodeLittlePrince 能说一下具体解决思路吗，我现在也是遇到这2个问题， @jmx164491960 你的这个参考链接打不开了

**Comment by CodeLittlePrince** [comment]
@yhlben 你可以查看我的commit，有详细的过程
